// <auto-generated />
using System;
using Iz.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IzDbContext))]
    [Migration("20260909001527_Faz3SyncSemasi")]
    partial class Faz3SyncSemasi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iz.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("push_token");

                    b.Property<int?>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Memories.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OccurredDay")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_day");

                    b.Property<int>("OccurredMonth")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_month");

                    b.Property<int>("OccurredYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_year");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("SourceJournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_journal_entry_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_memories");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_memories_owner_id");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryCollection", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MemoryId", "CollectionId")
                        .HasName("pk_memory_collections");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_memory_collections_collection_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_memory_collections_owner_id");

                    b.ToTable("memory_collections", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryMedia", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MemoryId", "MediaId")
                        .HasName("pk_memory_media");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_memory_media_media_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_memory_media_owner_id");

                    b.ToTable("memory_media", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryPerson", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Role")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MemoryId", "PersonId")
                        .HasName("pk_memory_people");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_memory_people_owner_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_memory_people_person_id");

                    b.ToTable("memory_people", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryRitual", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<Guid>("RitualId")
                        .HasColumnType("uuid")
                        .HasColumnName("ritual_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("OccurrenceYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_year");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MemoryId", "RitualId")
                        .HasName("pk_memory_rituals");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_memory_rituals_owner_id");

                    b.HasIndex("RitualId")
                        .HasDatabaseName("ix_memory_rituals_ritual_id");

                    b.ToTable("memory_rituals", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Sync.ChangeLogEntry", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Seq")
                        .HasName("pk_change_log");

                    b.HasIndex("UserId", "Seq")
                        .HasDatabaseName("ix_change_log_user_seq");

                    b.ToTable("change_log", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("PlanCache")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plan_cache");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_firebase_uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Iz.Domain.Devices.Device", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");
                });

            modelBuilder.Entity("Iz.Domain.Memories.Memory", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memories_users_owner_id");
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryCollection", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_collections_users_owner_id");
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryMedia", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_media_users_owner_id");
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryPerson", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_people_users_owner_id");
                });

            modelBuilder.Entity("Iz.Domain.Memories.MemoryRitual", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_rituals_users_owner_id");
                });

            modelBuilder.Entity("Iz.Domain.Sync.ChangeLogEntry", b =>
                {
                    b.HasOne("Iz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_log_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
